### PR TITLE
fix: pages button spacing

### LINKED ISSUE #3: buttons spacing
- There is no margin-right between the three dots and the button.
 - There is a margin-right between the last button and the navigation right arrow.

### PR DESCRIPTION
**Pull request by fdrissi**
Fix #3 

Fix that issue by adding a wrapper to the pages buttons that add a margin-right to all the children (including the three dots), except the last child

### CODE REVIEW

**Comment by smakosh** [comment]
Hey @fdrissi thanks for the quick contribution! Could we fix that spacing issue without adding an additional div? otherwise we will to let others override that pagesWrapper entirely like we do with the container prop.

**Comment by fdrissi** [comment]
For the moment, I don't think that we need to give the others the ability to override that wrapper, what we can do now IMHO is to allow them to pass the space between the buttons, so the default ```margin-right``` value will be ```4px```, but they can override it by passing ```buttonsSpacing: number``` prop, what do you think @smakosh?

**Comment by smakosh** [comment]
That's way too narrow IMO, I'll try to add the spacing without adding the additional div

**Comment by fdrissi** [comment]
you don't have to @smakosh, I will do it this evening

**Comment by smakosh** [comment]
Could you add an empty commit following semantic commit convention? `git commit --allow-empty -m "fix(spacing): add spacing for the separator"`?

**Review by smakosh — APPROVED** [review]
LGTM

**Comment by smakosh** [comment]
@all-contributors please add @fdrissi  for code

**Pull request merged**
